--QUERY14

SELECT C1.CID, C1.CNAME, SUM(P.TOTAL_PRICE) FROM CUSTOMERS C1, PURCHASES P

WHERE C1.CID=P.CID

AND C1.VISITS_MADE=(SELECT MAX(C2.VISITS_MADE) FROM CUSTOMERS C2)

GROUP BY C1.CID, C1.CNAME