--QUERY4

WITH TEMP_RES(PID) AS (SELECT PR.PID FROM PRODUCTS PR WHERE PNAME='TV')

SELECT * FROM PURCHASES PU

WHERE PU.PID NOT IN (SELECT T.PID FROM TEMP_RES T)

AND 0<(SELECT COUNT(*) FROM CUSTOMERS C, EMPLOYEES E 

       WHERE E.EID=PU.EID AND C.CID=PU.CID AND SUBSTR(C.TELEPHONE#,1,3)=SUBSTR(E.TELEPHONE#,1,3));