--QUERY13

WITH TEMP_RES(CID,PID) AS (SELECT DISTINCT P1.CID, P1.PID FROM PURCHASES P1, PURCHASES P2

                           WHERE P1.CID=P2.CID)

SELECT C.CID, C.CNAME, COUNT(T.PID)

FROM CUSTOMERS C, TEMP_RES T

WHERE C.CID=T.CID GROUP BY C.CID, C.CNAME