--QUERY10

WITH TEMP_RES(CID) AS (SELECT P1.CID FROM PURCHASES P1, PURCHASES P2 

                       WHERE P1.PID=P2.PID AND P2.CID='c003' AND P1.CID!='c003')

SELECT C.CID FROM CUSTOMERS C

WHERE C.CID IN (SELECT T.CID FROM TEMP_RES T);