SELECT E.EID, E.ENAME FROM EMPLOYEES E

WHERE NOT EXISTS ((SELECT C1.CID FROM CUSTOMERS C1 WHERE C1.VISITS_MADE>1)

      MINUS (SELECT DISTINCT P.CID FROM PURCHASES P, CUSTOMERS C2 WHERE P.CID=C2.CID AND E.EID=P.EID AND C2.VISITS_MADE>1));