--QUERY15

WITH TEMP_RES(CNAME,TOTAL_AMOUNT) AS (SELECT C.CNAME, SUM(P.TOTAL_PRICE) FROM CUSTOMERS C, PURCHASES P 

                                      WHERE C.CID=P.CID GROUP BY C.CID, C.CNAME)

SELECT T.CNAME, T.TOTAL_AMOUNT FROM TEMP_RES T 

ORDER BY T.TOTAL_AMOUNT DESC

FETCH FIRST 3 ROWS ONLY