--QUERY12

WITH TEMP_RES(CID) AS (SELECT DISTINCT P1.CID FROM PURCHASES P1 

                       WHERE P1.TOTAL_PRICE=(SELECT MAX(P2.TOTAL_PRICE) FROM PURCHASES P2))

SELECT C.CNAME FROM CUSTOMERS C

WHERE C.CID IN (SELECT T.CID FROM TEMP_RES T);