--QUERY3

WITH TEMP_RES(EID) AS (SELECT E.EID FROM EMPLOYEES E WHERE E.ENAME='Peter')

SELECT PR.PID, PR.PNAME FROM PRODUCTS PR

WHERE 20>(PR.ORIGINAL_PRICE*(1-PR.DISCNT_RATE))

AND PR.PID IN (SELECT PU.PID FROM PURCHASES PU WHERE PU.EID IN (SELECT T.EID FROM TEMP_RES T))